server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: catalog-service-route
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**

        - id: inventory-service-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**

        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: store-service-route
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/api/stores/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/ecommshoe

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/